[package]
name = "rex-player"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
ffmpeg-next = "7.1.0"
image = "0.25.5"
json = "0.12.4"
projectm = "3.1.2"
rand = "0.8.5"
rhai = "1.20.1"
rhai-fs = "0.1.3"
rhai-rand = "0.1.6"
xcb = { version="1.5.0", features=["present","randr"] }
