<media use-video=false id=bkg w=1px h=1px>??=next(eve,"Music","W.Nelson")??</>
<media use-audio=false id=q1 w=50pw h=50ph>??=next(eve,curlib,"")??</><media use-audio=false id=q2 w=50pw h=50ph l=50pw>??=next(eve,curlib,"")??</>
<media use-audio=false id=q3 t=50ph w=50pw h=50ph>??=next(eve,curlib,"")??</><media use-audio=false speed-factor=0.25 start-secs=-60 id=q4 t=50ph l=50pw w=50pw h=50ph>??=next(eve,curlib,"")??</>
<choices visible=false id=filter l=10pw t=10ph w=80pw h=80ph>??=shows(eve,curlib)??</>
<i id=more-bkg m=p.m>music</>