<media id=qfull w=100pw h=100ph>??=next(eve,curlib,"")??</>
<i id=show-unwatched>eye</><i id=show-lock l=l.r>lock</><lbl cnt-enum=Auto|4:3|21:9 id=season-fit l=l.r>Auto</><lbl id=aud-s l=l.r>(AUD)</>
<lbl m=p.m id=title></>
<blk c=p.c m=p.m w=192px h=64px>
    <i id=prev-show>angles-left</><i id=rnd-show l=l.r>arrows-spin</><i id=next-show l=l.r>angles-right</>
</>
<choices visible=false id=filter l=10pw t=10ph w=80pw h=80ph>??=shows(eve,curlib)??</>